= My concatenation-based video workflow

This is how I now produce tutorial videos, by creating separate videos for each chapter then putting them together. There's a degree of obviousness to the concept, however the technical details to achieve seemless transitions are tricky, so describing the process in sufficient detail is well-warranted.

== The problem

Creating YouTube videos that last several minutes or more containing many scenes can be difficult. There are two main problems with the naive approach:

- Having a large video project in your video editor. Things can get quickly complicated and worse, you might choose to avoid doing radical changes to the timeline for fear of having to readjust too many things.
- Rendering the large video all at once. Sure you can render only small sections to preview the result, but ultimately how will you see the video in its final state? By rendering the whole thing, which is going to take a long time every time, and you might find yourself doing that a lot more times than you expected.

== The solution

My solution is to produce "chapters" completely independently from each other, render them as independent files, then join them together using a batch file that puts all the chapters together in just a few seconds without generation loss (the video streams aren't re-encoded). Usually there's a natural 

== The workflow

To create scenes separately in Vegas Pro then put them together with ffmpeg the following must be done:

- The sound at the end of each scene must be trimmed to the previous video frame and the ends of the video and audio tracks must be aligned
- Make sure the ends of the audio track don't contain undesirable fade ins/outs added by the editor that would ruin the seemlessness.
- When exporting make sure the Vegas loop region isn't set. The loop region isn't contained in the project and it's kept when closing a project and opening another, so restarting Vegas will make it go away.
- Audio must be rendered separately to a WAV file, only as needed of course
- Video must be rendered separately to a MP4 file, all with the same encoding parameters of course, without sound because the audio of an MP4 would contain a silence padding at the start of about 44 milliseconds which would ruin everything
- Make two lists of files, one "video_concat_list.txt" and one "audio_concat_list.txt", put the files in order of appearance in each file, for instance put "file '01. First scene.mp4'" as the first line of "video_concat_list.txt"
- run "concat.bat", which calls ffmpeg, takes the two concat lists as inputs, concats the video streams without reencoding but concats the WAV sounds into a compressed stream, all into one final MP4 file.
